version: "3.8"

volumes:
  wordpress:
  mariadb:

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
     - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/www/html/index.php"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/www/html/wp-config.php"]
      interval: 10s
      timeout: 5s
      retries: 3

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 3
